### ISSUE TITLE
How to get white style of apple button if background is dark or black. 

### ISSUE THREAD

**Issue by akshaysahu001** [SystangoTechnologies/react-native-apple-authentication#18]

**Comment by amourya-systango** [comment]
You can use prop `buttonStyle` in which you can pass your own style with backgroundColor: white to make it white.

**Comment by ankitchauhan-react-native** [comment]
I have passed backgroundColor: 'white' but still getting black button. 
appleBtn: {
        height: 44,
        backgroundColor: 'white'

    },
Please help.

**Comment by akhilmorya** [comment]
Ok @ankitchauhan-react-native will check and update here

**Comment by ankitchauhan-react-native** [comment]
> Ok @ankitchauhan-react-native will check and update here

any update

**Comment by ankitchauhan-react-native** [comment]
can you please suggest how can be log out from the apple sign-in without following the manual step?

**Comment by VikramSingh1994** [comment]
Hi All,
If you can resolve this issue,
check given code snippets and edit the methods according your UI:-

Go To -> node_module -> react-native-apple-authentication ->
Hint- (this used for custom apple button on dark theme otherwise apple reject app)

export const SignInWithAppleButton = ({buttonText = '', callBack, buttonStyle={borderRadius: 5, justifyContent: 'center', alignItems: 'center', backgroundColor: 'black'}, textStyle={ fontSize : 19, color: "black", textAlign: 'center', marginTop: 10, marginBottom: 10, marginHorizontal: 20 }}) => {
  if(Platform.OS === 'ios') {
    if(buttonText) {
      return <TouchableOpacity style={buttonStyle} onPress={async () => {
          await appleAuth(callBack);
        }}
        >
          <Image
                  source={require('../../src/assets/other/LeftBlack.png')}
                  style={{height: 44, width: 44, resizeMode: 'contain',}}
         />
          <Text style = {textStyle}>
            {buttonText}
          </Text>
        </TouchableOpacity>
    } else {
      return <RNSignInWithAppleButton style={buttonStyle} onPress={async () => {
        await appleAuth(callBack);
      }} 
      />
    }
  } else {
    return null
  }
}

**Comment by amourya-systango** [comment]
Hello @ankitchauhan-react-native have you checked this example:
https://github.com/SystangoTechnologies/react-native-apple-authentication/blob/master/example/App.js

I have tested it back and when I change the style:
appleBtn: {    height: 44,     width: 200,    borderRadius: 5,     justifyContent: 'center',     alignItems: 'center',    backgroundColor: 'black'  }

to 

appleBtn: {    height: 44,     width: 200,    borderRadius: 5,     justifyContent: 'center',     alignItems: 'center',    backgroundColor: 'white'  }

Then it changes button background with white.

Please check if you have the latest RN version:

https://www.npmjs.com/package/react-native-apple-authentication -> 1.0.8

**Comment by amourya-systango** [comment]
I'm closing this PR. Please open it again if you find any issues here again. Hope the above answer will help.
